"""
The C runtime prelude, emitted inline into every generated file.

Two reasons it is inlined rather than shipped as a header:

  * the output is self-contained — `gcc out.c -lm -o out` just works, with no
    -I flag and no copy of pyrt.h next to it;
  * only the helpers a program actually uses are emitted, so the C you see
    beside your Python in the GUI stays readable.

Everything here exists because C's operators do *not* mean what Python's mean:

  Python            C                          why the helper exists
  ------            -                          ---------------------
  7 / 2   -> 3.5    7 / 2   -> 3               `/` is always true division
  -7 // 2 -> -4     -7 / 2  -> -3              `//` floors, C truncates
  -7 % 2  -> 1      -7 % 2  -> -1              `%` takes the divisor's sign
  1 / 0   -> raises 1 / 0   -> undefined       ZeroDivisionError
  print(3.5)-> 3.5  printf("%f") -> 3.500000   repr() picks the shortest form
  print(True)->True printf("%d") -> 1          bools print as words
  round(2.5)-> 2    round(2.5) -> 3            Python rounds halves to even

Each entry below is (dependencies, code). `prelude_for()` emits the transitive
closure in declaration order.
"""

from collections import OrderedDict

HEADER = """\
/* ------------------------------------------------------------------ *
 *  Generated by the hybrid Python-subset -> C compiler.
 *  Self-contained: build with `cc out.c -lm -o out` (no -I needed).
 * ------------------------------------------------------------------ */
#ifdef __MINGW32__
#  define __USE_MINGW_ANSI_STDIO 1   /* make %lld work with MinGW's printf */
#endif
#ifdef _MSC_VER
#  define _CRT_SECURE_NO_WARNINGS 1
#endif

#define _USE_MATH_DEFINES 1
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <math.h>
#include <limits.h>

#ifndef M_PI
#  define M_PI 3.14159265358979323846
#endif
#ifndef M_E
#  define M_E 2.7182818284590452354
#endif

/* Python's types, mapped onto C. `long long` rather than `int` because
 * Python integers are arbitrary precision; this at least gets 64 bits. */
typedef long long   py_int;
typedef double      py_float;
typedef const char *py_str;
typedef int         py_bool;

#define PY_INT_MIN LLONG_MIN
#define PY_INT_MAX LLONG_MAX
"""


HELPERS = OrderedDict()


def _helper(name, deps=()):
    def register(code):
        HELPERS[name] = (tuple(deps), code.rstrip() + "\n")
        return code
    return register


_helper("py_fatal")("""
/* Python raises; C has no exceptions, so an uncaught error stops the program
 * with the same message and exit status CPython would use. */
static void py_fatal(const char *msg)
{
    fflush(stdout);
    fprintf(stderr, "%s\\n", msg);
    exit(1);
}
""")


_helper("py_div_int", ["py_fatal"])("""
static py_float py_div_int(py_int a, py_int b)
{
    if (b == 0) py_fatal("ZeroDivisionError: division by zero");
    return (py_float)a / (py_float)b;
}
""")


_helper("py_div_float", ["py_fatal"])("""
static py_float py_div_float(py_float a, py_float b)
{
    if (b == 0.0) py_fatal("ZeroDivisionError: float division by zero");
    return a / b;
}
""")


_helper("py_floordiv_int", ["py_fatal"])("""
/* C truncates toward zero; Python floors. They differ whenever exactly one
 * operand is negative: -7 // 2 is -4 in Python but -3 in C. */
static py_int py_floordiv_int(py_int a, py_int b)
{
    py_int q;
    if (b == 0) py_fatal("ZeroDivisionError: integer division or modulo by zero");
    if (a == PY_INT_MIN && b == -1) py_fatal("OverflowError: integer division overflow");
    q = a / b;
    if ((a % b != 0) && ((a < 0) != (b < 0))) q--;
    return q;
}
""")


_helper("py_mod_int", ["py_fatal"])("""
/* Python's % takes the sign of the divisor: -7 % 2 is 1, not -1. */
static py_int py_mod_int(py_int a, py_int b)
{
    py_int r;
    if (b == 0) py_fatal("ZeroDivisionError: integer division or modulo by zero");
    if (a == PY_INT_MIN && b == -1) return 0;
    r = a % b;
    if (r != 0 && ((r < 0) != (b < 0))) r += b;
    return r;
}
""")


_helper("py_mod_float", ["py_fatal"])("""
/* Transliterated from CPython's float_rem (Objects/floatobject.c). */
static py_float py_mod_float(py_float a, py_float b)
{
    py_float mod;
    if (b == 0.0) py_fatal("ZeroDivisionError: float modulo");
    mod = fmod(a, b);
    if (mod != 0.0) {
        if ((b < 0) != (mod < 0)) mod += b;
    } else {
        mod = copysign(0.0, b);
    }
    return mod;
}
""")


_helper("py_floordiv_float", ["py_fatal"])("""
/* Transliterated from CPython's float_divmod, not simply floor(a / b):
 * computing the remainder first is what makes the edge cases agree. */
static py_float py_floordiv_float(py_float a, py_float b)
{
    py_float mod, div, floordiv;
    if (b == 0.0) py_fatal("ZeroDivisionError: float floor division by zero");
    mod = fmod(a, b);
    div = (a - mod) / b;
    if (mod != 0.0) {
        if ((b < 0) != (mod < 0)) {
            mod += b;
            div -= 1.0;
        }
    }
    if (div != 0.0) {
        floordiv = floor(div);
        if (div - floordiv > 0.5) floordiv += 1.0;
    } else {
        floordiv = copysign(0.0, a / b);
    }
    return floordiv;
}
""")


_helper("py_pow_int", ["py_fatal"])("""
/* Exponentiation by squaring. Python would widen to a bignum on overflow;
 * this wraps at 64 bits, which is the documented limit of the subset. */
static py_int py_pow_int(py_int base, py_int exp)
{
    unsigned long long result = 1ULL;
    unsigned long long b = (unsigned long long)base;
    unsigned long long e;
    if (exp < 0)
        py_fatal("ValueError: int ** negative int produces a float; "
                 "make the base a float (e.g. 2.0 ** -1)");
    e = (unsigned long long)exp;
    while (e != 0ULL) {
        if (e & 1ULL) result *= b;
        b *= b;
        e >>= 1;
    }
    return (py_int)result;
}
""")


_helper("py_pow_float", ["py_fatal"])("""
static py_float py_pow_float(py_float base, py_float exp)
{
    if (base == 0.0 && exp < 0.0)
        py_fatal("ZeroDivisionError: 0.0 cannot be raised to a negative power");
    if (base < 0.0 && exp != floor(exp))
        py_fatal("ValueError: a negative number raised to a fractional power is complex, "
                 "which is not part of this subset");
    return pow(base, exp);
}
""")


_helper("py_abs_int", ["py_fatal"])("""
static py_int py_abs_int(py_int v)
{
    if (v == PY_INT_MIN) py_fatal("OverflowError: abs() of the most negative integer");
    return v < 0 ? -v : v;
}
""")


_helper("py_min_int")("""
static py_int py_min_int(py_int a, py_int b) { return a < b ? a : b; }
""")

_helper("py_max_int")("""
static py_int py_max_int(py_int a, py_int b) { return a > b ? a : b; }
""")

_helper("py_min_float")("""
static py_float py_min_float(py_float a, py_float b) { return a < b ? a : b; }
""")

_helper("py_max_float")("""
static py_float py_max_float(py_float a, py_float b) { return a > b ? a : b; }
""")


_helper("py_round_half_even")("""
/* Python rounds halves to even: round(0.5) == 0, round(2.5) == 2, round(3.5) == 4.
 * C's round() goes half away from zero, so the tie is corrected explicitly.
 * Transliterated from CPython's float___round___impl. */
static py_float py_round_half_even(py_float x)
{
    py_float r = round(x);
    if (fabs(x - r) == 0.5) r = 2.0 * round(x / 2.0);
    return r;
}
""")


_helper("py_round_int", ["py_round_half_even", "py_fatal"])("""
static py_int py_round_int(py_float x)
{
    py_float r;
    if (isnan(x)) py_fatal("ValueError: cannot convert float NaN to integer");
    if (isinf(x)) py_fatal("OverflowError: cannot convert float infinity to integer");
    r = py_round_half_even(x);
    if (r < -9.2233720368547758e18 || r > 9.2233720368547758e18)
        py_fatal("OverflowError: rounded value too large for a 64-bit integer");
    return (py_int)r;
}
""")


_helper("py_round_float", ["py_round_half_even"])("""
static py_float py_round_float(py_float x, py_int ndigits)
{
    if (!isfinite(x)) return x;
    if (ndigits >= 0) {
        char buf[512];
        if (ndigits > 17) return x;          /* beyond a double's precision */
        snprintf(buf, sizeof buf, "%.*f", (int)ndigits, x);
        return strtod(buf, NULL);
    } else {
        py_float scale;
        if (ndigits < -308) return 0.0 * x;  /* preserves the sign of zero */
        scale = pow(10.0, (py_float)(-ndigits));
        return py_round_half_even(x / scale) * scale;
    }
}
""")


_helper("py_round_int_ndigits")("""
/* round(int, ndigits): Python keeps the value an int and still rounds halves
 * to even, so round(1250, -2) is 1200 but round(1350, -2) is 1400. */
static py_int py_round_int_ndigits(py_int x, py_int nd)
{
    py_int scale = 1, i, q, r;
    if (nd >= 0) return x;
    if (nd < -18) return 0;
    for (i = 0; i < -nd; i++) scale *= 10;
    q = x / scale;
    r = x % scale;
    if (r < 0) { r += scale; q -= 1; }       /* floor form: 0 <= r < scale */
    if (2 * r > scale || (2 * r == scale && (q % 2) != 0)) q += 1;
    return q * scale;
}
""")


_helper("py_int_from_float", ["py_fatal"])("""
static py_int py_int_from_float(py_float x)
{
    py_float t;
    if (isnan(x)) py_fatal("ValueError: cannot convert float NaN to integer");
    if (isinf(x)) py_fatal("OverflowError: cannot convert float infinity to integer");
    t = trunc(x);                            /* int() truncates toward zero */
    if (t < -9.2233720368547758e18 || t > 9.2233720368547758e18)
        py_fatal("OverflowError: float too large to convert to a 64-bit integer");
    return (py_int)t;
}
""")


_helper("py_int_from_str", ["py_fatal"])("""
static py_int py_int_from_str(py_str s)
{
    char *end;
    long long v;
    if (s == NULL) py_fatal("ValueError: invalid literal for int()");
    v = strtoll(s, &end, 10);
    if (end == s) py_fatal("ValueError: invalid literal for int() with base 10");
    while (*end == ' ' || *end == '\\t' || *end == '\\n' || *end == '\\r') end++;
    if (*end != '\\0') py_fatal("ValueError: invalid literal for int() with base 10");
    return (py_int)v;
}
""")


_helper("py_float_from_str", ["py_fatal"])("""
static py_float py_float_from_str(py_str s)
{
    char *end;
    py_float v;
    if (s == NULL) py_fatal("ValueError: could not convert string to float");
    v = strtod(s, &end);
    if (end == s) py_fatal("ValueError: could not convert string to float");
    while (*end == ' ' || *end == '\\t' || *end == '\\n' || *end == '\\r') end++;
    if (*end != '\\0') py_fatal("ValueError: could not convert string to float");
    return v;
}
""")


_helper("py_truthy_str")("""
static py_bool py_truthy_str(py_str s) { return s != NULL && s[0] != '\\0'; }
""")


_helper("py_repr_float")("""
/* repr() of a float: the shortest decimal string that reads back as the same
 * double, which is why print(0.1) is "0.1" and not "0.100000".
 *
 * Mirrors CPython's format_float_short: find the smallest precision that
 * round-trips, then use positional notation when the decimal exponent is in
 * [-4, 16) and scientific notation outside it. */
static void py_repr_float(char *out, size_t cap, py_float v)
{
    char tmp[64];
    const char *epos;
    int p, exp10, dec;

    if (isnan(v)) { snprintf(out, cap, "nan"); return; }
    if (isinf(v)) { snprintf(out, cap, v < 0 ? "-inf" : "inf"); return; }

    for (p = 1; p < 17; p++) {
        snprintf(tmp, sizeof tmp, "%.*e", p - 1, v);
        if (strtod(tmp, NULL) == v) break;
    }
    snprintf(tmp, sizeof tmp, "%.*e", p - 1, v);

    epos = strchr(tmp, 'e');
    exp10 = epos ? (int)strtol(epos + 1, NULL, 10) : 0;

    if (exp10 >= -4 && exp10 < 16) {
        dec = p - 1 - exp10;
        if (dec < 0) dec = 0;
        snprintf(out, cap, "%.*f", dec, v);
        if (strchr(out, '.') == NULL) {
            size_t n = strlen(out);
            if (n + 3 <= cap) { out[n] = '.'; out[n + 1] = '0'; out[n + 2] = '\\0'; }
        }
    } else {
        snprintf(out, cap, "%s", tmp);
    }
}
""")


# print() writes its arguments separated by a single space and ends the line.
# C cannot dispatch on type, so codegen emits one call per argument and asks
# only for the per-type helpers the program actually uses.

_helper("py_print")("""
/* print() support: one call per argument, separated by a single space. */
static int py__print_first = 1;

static void py_print_begin(void) { py__print_first = 1; }

static void py__print_sep(void)
{
    if (!py__print_first) putchar(' ');
    py__print_first = 0;
}

static void py_print_end(void) { putchar('\\n'); py__print_first = 1; }
""")


_helper("py_print_int", ["py_print"])("""
static void py_print_int(py_int v) { py__print_sep(); printf("%lld", (long long)v); }
""")


_helper("py_print_bool", ["py_print"])("""
static void py_print_bool(py_bool v) { py__print_sep(); fputs(v ? "True" : "False", stdout); }
""")


_helper("py_print_str", ["py_print"])("""
static void py_print_str(py_str s) { py__print_sep(); fputs(s ? s : "", stdout); }
""")


_helper("py_print_float", ["py_print", "py_repr_float"])("""
static void py_print_float(py_float v)
{
    char buf[64];
    py_repr_float(buf, sizeof buf, v);
    py__print_sep();
    fputs(buf, stdout);
}
""")


def prelude_for(needed) -> str:
    """Return the header plus every requested helper and its dependencies,
    in declaration order."""
    resolved = []
    seen = set()

    def add(name):
        if name in seen:
            return
        if name not in HELPERS:
            raise KeyError(f"unknown runtime helper {name!r}")
        seen.add(name)
        for dep in HELPERS[name][0]:
            add(dep)
        resolved.append(name)

    for name in HELPERS:            # fixed order, independent of request order
        if name in needed:
            add(name)

    parts = [HEADER]
    if resolved:
        parts.append("\n/* ---- runtime helpers ---- */\n")
        for name in resolved:
            parts.append(HELPERS[name][1])
    return "".join(parts)
